version: '3.4'

services:
  djangojoplinvieweb:
    image: djangojoplinvieweb
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    command: ["sh", "-c", "pip install debugpy -t /tmp && python manage.py collectstatic --noinput && python manage.py migrate && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8001 --nothreading --noreload"]
    depends_on:
      - joplin-terminal-xapi
    volumes:
      - joplin-dev:/root/.config/joplin:ro
    ports:
      - 8001:8001
      - 5678:5678

  joplin-terminal-xapi:
    build: ../joplin-terminal-xapi
    volumes:
      - joplin-dev:/root/.config/joplin

volumes:
  joplin-dev: