version: '3.4'

services:
  djangojoplinvieweb:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    command: ["sh", "-c", "pip install debugpy -t /tmp && python manage.py collectstatic --noinput && python manage.py migrate && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8001 --nothreading --noreload"]
    # command: ["/bin/sh"]
    # stdin_open: true
    # tty: true 
    depends_on:
      - joplin-terminal-xapi
    volumes:
      - joplin-dev:/root/.config/joplin:ro
      - joplin-vieweb-dev:/root/.config/joplin-vieweb
      - type: bind
        source: ./joplin_vieweb
        target: /app/joplin_vieweb
        read_only: true
    ports:
      - 8001:8001
      - 5678:5678

  joplin-terminal-xapi:
    build: 
      context: ../joplin-terminal-xapi
      dockerfile: Dockerfile-dev
    # environment:
    #   NODE_ENV: production
    #   NODE_ENV: development
    # command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
    # command: ["npm", "start"]
    ports:
      - 8081:8081
      - 9229:9229
    volumes:
      - joplin-dev:/root/.config/joplin

volumes:
  joplin-dev:
  joplin-vieweb-dev:
