FROM python:3.9-alpine as compile-image
# Install pip requirements
COPY requirements.txt .
RUN apk add --virtual .build-deps gcc libffi-dev musl-dev
RUN pip install --user -r requirements.txt


FROM python:3.9-alpine

EXPOSE 8000

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

COPY --from=compile-image /root/.local /root/.local
ENV PATH=/root/.local/bin:$PATH

WORKDIR /app
RUN django-admin startproject server .
COPY ./settings /app/settings
RUN rm ./server/settings.py
RUN rm ./server/urls.py
RUN cp ./settings/urls-dev.py ./server/urls.py
RUN cp ./settings/settings-dev.py ./server/settings.py
COPY . /app

